server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Tipos de archivos para el motor de Flutter
    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
    }

    # Gzip extrema para minimizar la transferencia de datos
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types 
        text/plain 
        text/css 
        text/javascript 
        application/javascript 
        application/x-javascript 
        application/json 
        application/xml 
        application/wasm 
        image/svg+xml;

    # Cache agresivo para archivos estáticos (JS, WASM, Imágenes)
    location ~* \.(js|wasm|css|png|jpg|jpeg|gif|ico|svg|json|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}

