server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip compresión para optimizar descargas de JS/CSS de Flutter
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml image/svg+xml;
    gzip_disable "MSIE [1-6]\.";

    # Cache Control para los assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Redirigir todas las rutas al index.html para soportar navegación del lado del cliente
    location / {
        try_files $uri $uri/ /index.html;
    }
}
