import 'dart:html' as html;
import 'env_config.dart';

EnvPlatform get platformEnv => EnvConfigWeb();

class EnvConfigWeb implements EnvPlatform {
  @override
  String getApiUrl() => _getFromJS('API_URL') ?? 'https://api.katrix.com.ar';

  @override
  String getMpAccessToken() => _getFromJS('MP_ACCESS_TOKEN') ?? '';

  @override
  String getMpPublicKey() => _getFromJS('MP_PUBLIC_KEY') ?? '';

  String? _getFromJS(String key) {
    try {
      // Check localStorage first (can be useful for persistence/manual override)
      final env = html.window.localStorage['ENV_$key'];
      if (env != null && env.isNotEmpty) return env;
      
      // Fallback to window.ENV (generated by entrypoint.sh)
      final dynamic envObj = (html.window as dynamic).ENV;
      if (envObj != null) {
        return envObj[key]?.toString();
      }
    } catch (e) {
      print('Error reading $key from JS: $e');
    }
    return null;
  }
}
